const sentenceData = {
  week1: [
    // 1번
    {
      id: 'sentence1',
      level: 1,
      isFinal: false,
      korean: '꾸준히 해야 한다.',
      chinese: {
        hanzi: ['要', '坚持'],
        pinyin: ['yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 2,
      isFinal: false,
      korean: '공부는 꾸준히 해야 한다.',
      chinese: {
        hanzi: ['学习', '要', '坚持'],
        pinyin: ['xuéxí', 'yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 3,
      isFinal: false,
      korean: '공부는 꾸준히 해야 하고, ...하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú yào'],
      },
    },
    {
      id: 'sentence1',
      level: 4,
      isFinal: true,
      korean: '공부는 꾸준히 해야 하고, 중간에 포기하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要', '半途', '而', '废'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú', 'yào', 'bàntú', 'ér', 'fèi'],
      },
    },

    // 2번
    {
      id: 'sentence2',
      level: 1,
      isFinal: false,
      korean: '많이 피곤하다.',
      chinese: {
        hanzi: ['很', '累'],
        pinyin: ['hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 2,
      isFinal: false,
      korean: '비록 많이 피곤하지만, ......',
      chinese: {
        hanzi: ['尽管', '很', '累'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 3,
      isFinal: false,
      korean: '비록 많이 피곤하지만, 그래도 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '做', '完'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi', 'yě', 'yào', 'zuò', 'wán'],
      },
    },
    {
      id: 'sentence2',
      level: 4,
      isFinal: true,
      korean: '비록 많이 피곤하지만, 그래도 일을 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '把', '工作', '做', '完'],
        pinyin: [
          'jǐnguǎn',
          'hěn',
          'lèi',
          'yě',
          'yào',
          'bǎ',
          'gōngzuò',
          'zuò',
          'wán',
        ],
      },
    },

    // 3번
    {
      id: 'sentence3',
      level: 1,
      isFinal: false,
      korean: '시간을 바꾸다.',
      chinese: {
        hanzi: ['改', '时间'],
        pinyin: ['gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 2,
      isFinal: false,
      korean: '갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['临时', '改', '时间'],
        pinyin: ['línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 3,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 4,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 5,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '又', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'yòu', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 6,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '我们', '又', '得', '加班'],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
        ],
      },
    },
    {
      id: 'sentence3',
      level: 7,
      isFinal: true,
      korean:
        '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 해. 짜증 나지 않냐.',
      chinese: {
        hanzi: [
          '领导',
          '临时',
          '改',
          '时间',
          '我们',
          '又',
          '得',
          '加班',
          '你',
          '说',
          '烦',
          '不烦',
        ],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
          'nǐ',
          'shuō',
          'fán',
          'bu fán',
        ],
      },
    },
    // 4번
    {
      id: 'sentence4',
      level: 1,
      isFinal: false,
      korean: '선택을 하지 못하다.',
      chinese: {
        hanzi: ['做', '不', '出', '选择'],
        pinyin: ['zuò', 'bu', 'chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 2,
      isFinal: false,
      korean: '지금 선택을 하지 못하고 있다.',
      chinese: {
        hanzi: ['现在', '做', '不', '出', '选择'],
        pinyin: ['xiànzài', 'zuò', 'bu', 'chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 3,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면……',
      chinese: {
        hanzi: ['现在', '做', '不', '出', '选择', '换', '句', '话', '说'],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 4,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상……',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就',
          '是',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù',
          'shì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 5,
      isFinal: false,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就',
          '是',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù',
          'shì',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 6,
      isFinal: true,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하고 있는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就',
          '是',
          '在',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù',
          'shì',
          'zài',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    // 5번
    {
      id: 'sentence5',
      level: 1,
      isFinal: false,
      korean: '가격이 비싸다.',
      chinese: {
        hanzi: ['价格', '贵'],
        pinyin: ['jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 2,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데……',
      chinese: {
        hanzi: ['不', '怕', '价格', '贵'],
        pinyin: ['bú', 'pà', 'jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 3,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데, ……이 걱정이다.',
      chinese: {
        hanzi: ['不', '怕', '价格', '贵', '就', '怕'],
        pinyin: ['bú', 'pà', 'jiàgé', 'guì', 'jiù', 'pà'],
      },
    },
    {
      id: 'sentence5',
      level: 4,
      isFinal: true,
      korean: '가격이 비싼 건 괜찮은데, 품질이 안 좋을까 봐 걱정이다.',
      chinese: {
        hanzi: ['不', '怕', '价格', '贵', '就', '怕', '质量', '不', '好'],
        pinyin: [
          'bú',
          'pà',
          'jiàgé',
          'guì',
          'jiù',
          'pà',
          'zhìliàng',
          'bù',
          'hǎo',
        ],
      },
    },
    {
      id: 'sentence6',
      level: 1,
      isFinal: false,
      korean: '환경(분위기)이 좋다.',
      chinese: {
        hanzi: ['环境', '好'],
        pinyin: ['huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 2,
      isFinal: false,
      korean: '이 식당은 분위기가 좋다.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 3,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好', '是好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo', 'shì hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 4,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好', '是好', '可'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo', 'shì hǎo', 'kě'],
      },
    },
    {
      id: 'sentence6',
      level: 5,
      isFinal: true,
      korean: '이 식당 분위기는 좋긴 한데, (근데) 맛은 평범해.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好', '是好', '可', '味道', '一般'],
        pinyin: [
          'zhè',
          'jiā',
          'cāntīng',
          'huánjìng',
          'hǎo',
          'shì hǎo',
          'kě',
          'wèidào',
          'yìbān',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 1,
      isFinal: false,
      korean: '도착했다.',
      chinese: {
        hanzi: ['到', '了'],
        pinyin: ['dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 2,
      isFinal: false,
      korean: '제시간에 도착했다.',
      chinese: {
        hanzi: ['准时', '到', '了'],
        pinyin: ['zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 3,
      isFinal: false,
      korean: '설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['居然', '准时', '到', '了'],
        pinyin: ['jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 4,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['你', '居然', '准时', '到', '了'],
        pinyin: ['nǐ', 'jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 5,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고? 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 6,
      isFinal: true,
      korean: '네가 설마 제시간에 도착했다고? 진짜 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '真是',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'zhēnshì',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence8',
      level: 1,
      isFinal: false,
      korean: '걱정하다.',
      chinese: {
        hanzi: ['担心'],
        pinyin: ['dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 2,
      isFinal: false,
      korean: '걱정하지 마.',
      chinese: {
        hanzi: ['别', '担心'],
        pinyin: ['bié', 'dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 3,
      isFinal: true,
      korean: '걱정 마, 내가 있잖아.',
      chinese: {
        hanzi: ['别', '担心', '有', '我', '呢'],
        pinyin: ['bié', 'dānxīn', 'yǒu', 'wǒ', 'ne'],
      },
    },
    {
      id: 'sentence9',
      level: 1,
      isFinal: false,
      korean: '나에게 알려줘.',
      chinese: {
        hanzi: ['告诉', '我'],
        pinyin: ['gàosu', 'wǒ'],
      },
    },
    {
      id: 'sentence9',
      level: 2,
      isFinal: false,
      korean: '나에게 알려줘(봐).',
      chinese: {
        hanzi: ['告诉', '我', '吧'],
        pinyin: ['gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 3,
      isFinal: false,
      korean: '미리 나한테 알려줘.',
      chinese: {
        hanzi: ['提前', '告诉', '我', '吧'],
        pinyin: ['tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 4,
      isFinal: false,
      korean: '미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['得', '提前', '告诉', '我', '吧'],
        pinyin: ['děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 5,
      isFinal: false,
      korean: '어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['怎么', '说', '也', '得', '提前', '告诉', '我', '吧'],
        pinyin: ['zěnme', 'shuō', 'yě', 'děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 6,
      isFinal: true,
      korean: '그는 아무리 바빠도, 어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: [
          '他',
          '再',
          '忙',
          '怎么',
          '说',
          '也',
          '得',
          '提前',
          '告诉',
          '我',
          '吧',
        ],
        pinyin: [
          'tā',
          'zài',
          'máng',
          'zěnme',
          'shuō',
          'yě',
          'děi',
          'tíqián',
          'gàosu',
          'wǒ',
          'ba',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 1,
      isFinal: false,
      korean: '지금은 …할 때다.',
      chinese: {
        hanzi: ['现在', '是', '时候'],
        pinyin: ['xiànzài', 'shì', 'shíhou'],
      },
    },
    {
      id: 'sentence10',
      level: 2,
      isFinal: false,
      korean: '이제는 …할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了'],
        pinyin: ['xiànzài', 'shì', 'shíhou', 'le'],
      },
    },
    {
      id: 'sentence10',
      level: 3,
      isFinal: false,
      korean: '이제는 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '得', '谈', '一谈'],
        pinyin: ['xiànzài', 'shì', 'shíhou', 'le', 'děi', 'tán', 'yi tán'],
      },
    },
    {
      id: 'sentence10',
      level: 4,
      isFinal: false,
      korean: '이제는 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '得', '认真', '谈', '一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'děi',
          'rènzhēn',
          'tán',
          'yi tán',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 5,
      isFinal: true,
      korean: '이제는 우리 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '我们', '得', '认真', '谈', '一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'wǒmen',
          'děi',
          'rènzhēn',
          'tán',
          'yi tán',
        ],
      },
    },
  ],

  week2: [
    // 11번
    {
      id: 'sentence6',
      level: 1,
      isFinal: false,
      korean: '경기에 참가하다.',
      chinese: {
        hanzi: ['参加', '比赛'],
        pinyin: ['cānjiā', 'bǐsài'],
      },
    },
    {
      id: 'sentence6',
      level: 2,
      isFinal: false,
      korean: '경기에 참가하지 않다.',
      chinese: {
        hanzi: ['不', '参加', '比赛'],
        pinyin: ['bù', 'cānjiā', 'bǐsài'],
      },
    },
    {
      id: 'sentence6',
      level: 3,
      isFinal: false,
      korean: '(이제) 경기에 참가하지 않게 되었다.',
      chinese: {
        hanzi: ['不', '参加', '比赛', '了'],
        pinyin: ['bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 4,
      isFinal: false,
      korean: '(이제) 경기에 참가하지 않는 거야?',
      chinese: {
        hanzi: ['是不是', '不', '参加', '比赛', '了'],
        pinyin: ['shì bu shì', 'bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 5,
      isFinal: true,
      korean: 'A: 걔는 (이제) 경기에 참가하지 않는 거야?',
      chinese: {
        hanzi: ['他', '是不是', '不', '参加', '比赛', '了'],
        pinyin: ['tā', 'shì bu shì', 'bù', 'cānjiā', 'bǐsài', 'le'],
      },
    },
    {
      id: 'sentence6',
      level: 6,
      isFinal: false,
      korean: '훈련에 오다.',
      chinese: {
        hanzi: ['来', '训练'],
        pinyin: ['lái', 'xùnliàn'],
      },
    },
    {
      id: 'sentence6',
      level: 7,
      isFinal: false,
      korean: '훈련에 안 왔다.',
      chinese: {
        hanzi: ['没', '来', '训练'],
        pinyin: ['méi', 'lái', 'xùnliàn'],
      },
    },
    {
      id: 'sentence6',
      level: 8,
      isFinal: false,
      korean: '이렇게 오랫동안 훈련에 안 나왔다.',
      chinese: {
        hanzi: ['这么', '久', '没', '来', '训练了'],
        pinyin: ['zhème', 'jiǔ', 'méi', 'lái', 'xùnliàn le'],
      },
    },
    {
      id: 'sentence6',
      level: 9,
      isFinal: false,
      korean: '이미 이렇게 오래 훈련에 안 나왔는데, ......',
      chinese: {
        hanzi: ['都', '这么', '久', '没', '来', '训练了, ......'],
        pinyin: ['dōu', 'zhème', 'jiǔ', 'méi', 'lái', 'xùnliàn le'],
      },
    },
    {
      id: 'sentence6',
      level: 10,
      isFinal: false,
      korean: '이미 이렇게 오래 훈련에 안 나왔는데, 분명 그렇지.',
      chinese: {
        hanzi: ['都', '这么', '久', '没', '来', '训练', '了', '肯定', '是'],
        pinyin: [
          'dōu',
          'zhème',
          'jiǔ',
          'méi',
          'lái',
          'xùnliàn',
          'le',
          'kěndìng',
          'shì',
        ],
      },
    },
    {
      id: 'sentence6',
      level: 11,
      isFinal: true,
      korean: 'B: 너 생각엔? 이미 이렇게 오래 훈련에 안 나왔는데, 분명 그렇지.',
      chinese: {
        hanzi: [
          '你',
          '说',
          '呢',
          '都',
          '这么',
          '久',
          '没',
          '来',
          '训练',
          '了',
          '肯定',
          '是',
        ],
        pinyin: [
          'nǐ',
          'shuō',
          'ne',
          'dōu',
          'zhème',
          'jiǔ',
          'méi',
          'lái',
          'xùnliàn',
          'le',
          'kěndìng',
          'shì',
        ],
      },
    },

    // 2번
    {
      id: 'sentence7',
      level: 1,
      isFinal: false,
      korean: '시간 있어.',
      chinese: {
        hanzi: ['有', '空'],
        pinyin: ['yǒu', 'kòng'],
      },
    },
    {
      id: 'sentence7',
      level: 2,
      isFinal: false,
      korean: '시간 있어?',
      chinese: {
        hanzi: ['有', '空', '吗'],
        pinyin: ['yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 3,
      isFinal: false,
      korean: '내일 시간 있어?',
      chinese: {
        hanzi: ['明天', '有', '空', '吗'],
        pinyin: ['míngtiān', 'yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 4,
      isFinal: true,
      korean: 'A: 너 내일 시간 있어?',
      chinese: {
        hanzi: ['你', '明天', '有', '空', '吗'],
        pinyin: ['nǐ', 'míngtiān', 'yǒu', 'kòng', 'ma'],
      },
    },
    {
      id: 'sentence7',
      level: 5,
      isFinal: false,
      korean: '일정을 보다.',
      chinese: {
        hanzi: ['看', '日程'],
        pinyin: ['kàn', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 6,
      isFinal: false,
      korean: '일정 한번 볼게.',
      chinese: {
        hanzi: ['看看', '日程'],
        pinyin: ['kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 7,
      isFinal: false,
      korean: '나 일정 한번 볼게.',
      chinese: {
        hanzi: ['我', '看看', '日程'],
        pinyin: ['wǒ', 'kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 8,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程'],
        pinyin: ['nà ge', 'wǒ', 'kànkan', 'rìchéng'],
      },
    },
    {
      id: 'sentence7',
      level: 9,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게. 오후에 돼.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程', '下午', '可以'],
        pinyin: ['nà ge', 'wǒ', 'kànkan', 'rìchéng', 'xiàwǔ', 'kěyǐ'],
      },
    },
    {
      id: 'sentence7',
      level: 10,
      isFinal: false,
      korean: '그… 나 일정 한번 볼게. 오후에 될 것 같아.',
      chinese: {
        hanzi: ['那个', '我', '看看', '日程', '下午', '好像', '可以'],
        pinyin: [
          'nà ge',
          'wǒ',
          'kànkan',
          'rìchéng',
          'xiàwǔ',
          'hǎoxiàng',
          'kěyǐ',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 11,
      isFinal: true,
      korean: 'B: 내일… 그… 나 일정 한번 볼게. 오후에 될 것 같아.',
      chinese: {
        hanzi: [
          '明天啊... ',
          '那个',
          '我',
          '看看',
          '日程',
          '下午',
          '好像',
          '可以',
        ],
        pinyin: [
          'míngtiān a',
          'nà ge',
          'wǒ',
          'kànkan',
          'rìchéng',
          'xiàwǔ',
          'hǎoxiàng',
          'kěyǐ',
        ],
      },
    },

    // 3번
    {
      id: 'sentence8',
      level: 1,
      isFinal: false,
      korean: '지금 하는 일',
      chinese: {
        hanzi: ['现在', '的', '工作'],
        pinyin: ['xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 2,
      isFinal: false,
      korean: '지금 하는 일을 좋아해.',
      chinese: {
        hanzi: ['喜欢', '现在', '的', '工作'],
        pinyin: ['xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 3,
      isFinal: false,
      korean: '지금 하는 일을 좋아해?',
      chinese: {
        hanzi: ['喜不喜欢', '现在', '的', '工作'],
        pinyin: ['xǐ bu xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 4,
      isFinal: true,
      korean: 'A: 너 지금 하는 일을 좋아해?(좋아해 안 좋아해?)',
      chinese: {
        hanzi: ['你', '喜', '不', '喜欢', '现在', '的', '工作'],
        pinyin: ['nǐ', 'xǐ', 'bu', 'xǐhuan', 'xiànzài', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence8',
      level: 5,
      isFinal: false,
      korean: '좋은 점도 있고 나쁜 점도 있어.',
      chinese: {
        hanzi: ['有好有坏'],
        pinyin: ['yǒu hǎo yǒu huài'],
      },
    },
    {
      id: 'sentence8',
      level: 6,
      isFinal: false,
      korean: '좋은 점도 있고 나쁜 점도 있지.',
      chinese: {
        hanzi: ['有好', '有坏', '吧'],
        pinyin: ['yǒu hǎo', 'yǒu huài', 'ba'],
      },
    },
    {
      id: 'sentence8',
      level: 7,
      isFinal: true,
      korean: 'B: 어떻게 말해야 할까… 좋은 점도 있고 나쁜 점도 있지.',
      chinese: {
        hanzi: ['怎么', '说', '呢', '有好', '有坏', '吧'],
        pinyin: ['zěnme', 'shuō', 'ne', 'yǒu hǎo', 'yǒu huài', 'ba'],
      },
    },
    // 4번
    {
      id: 'sentence9',
      level: 1,
      isFinal: false,
      korean: '여행 가다.',
      chinese: {
        hanzi: ['去', '旅行'],
        pinyin: ['qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 2,
      isFinal: false,
      korean: '같이 여행 가다.',
      chinese: {
        hanzi: ['一起', '去', '旅行'],
        pinyin: ['yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 3,
      isFinal: false,
      korean: '같이 여행 갈래?',
      chinese: {
        hanzi: ['要不要', '一起', '去', '旅行'],
        pinyin: ['yào bu yào', 'yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 4,
      isFinal: true,
      korean: 'A: 주말에 같이 여행 갈래?',
      chinese: {
        hanzi: ['周末', '要不要', '一起', '去', '旅行'],
        pinyin: ['zhōumò', 'yào bu yào', 'yìqǐ', 'qù', 'lǚxíng'],
      },
    },
    {
      id: 'sentence9',
      level: 5,
      isFinal: false,
      korean: '시간을 좀 보다.',
      chinese: {
        hanzi: ['看看', '时间'],
        pinyin: ['kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 6,
      isFinal: false,
      korean: '시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['得', '看看', '时间'],
        pinyin: ['děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 7,
      isFinal: false,
      korean: '나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['我', '得', '看看', '时间'],
        pinyin: ['wǒ', 'děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 8,
      isFinal: false,
      korean: '이건 말이지…… 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['这个嘛', '我', '得', '看看', '时间'],
        pinyin: ['zhè ge ma', 'wǒ', 'děi', 'kànkan', 'shíjiān'],
      },
    },
    {
      id: 'sentence9',
      level: 9,
      isFinal: false,
      korean: '이건 말이지…… 일이 좀 많아서, 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: ['这个嘛', '事情', '有点', '多', '我', '得', '看看', '时间'],
        pinyin: [
          'zhè ge ma',
          'shìqing',
          'yǒudiǎn',
          'duō',
          'wǒ',
          'děi',
          'kànkan',
          'shíjiān',
        ],
      },
    },
    {
      id: 'sentence9',
      level: 10,
      isFinal: true,
      korean: 'B: 이건 말이지…… 요즘 일이 좀 많아서, 나는 시간을 좀 봐야 해.',
      chinese: {
        hanzi: [
          '这个嘛',
          '最近',
          '事情',
          '有点',
          '多',
          '我',
          '得',
          '看看',
          '时间',
        ],
        pinyin: [
          'zhè ge ma',
          'zuìjìn',
          'shìqing',
          'yǒudiǎn',
          'duō',
          'wǒ',
          'děi',
          'kànkan',
          'shíjiān',
        ],
      },
    },
    // 5번
    {
      id: 'sentence10',
      level: 1,
      isFinal: false,
      korean: '나를 도와줘.',
      chinese: {
        hanzi: ['帮', '我'],
        pinyin: ['bāng', 'wǒ'],
      },
    },
    {
      id: 'sentence10',
      level: 2,
      isFinal: false,
      korean: '나를 좀 도와줘.',
      chinese: {
        hanzi: ['帮', '我', '一下'],
        pinyin: ['bāng', 'wǒ', 'yíxià'],
      },
    },
    {
      id: 'sentence10',
      level: 3,
      isFinal: false,
      korean: '나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['能', '帮', '我', '一下', '吗'],
        pinyin: ['néng', 'bāng', 'wǒ', 'yíxià', 'ma'],
      },
    },
    {
      id: 'sentence10',
      level: 4,
      isFinal: false,
      korean: '너는 나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['你', '能', '帮', '我', '一下', '吗'],
        pinyin: ['nǐ', 'néng', 'bāng', 'wǒ', 'yíxià', 'ma'],
      },
    },
    {
      id: 'sentence10',
      level: 5,
      isFinal: true,
      korean: 'A: 이번 주말에 너는 나를 좀 도와줄 수 있어?',
      chinese: {
        hanzi: ['这', '个', '周末', '你', '能', '帮', '我', '一下', '吗'],
        pinyin: [
          'zhè',
          'ge',
          'zhōumò',
          'nǐ',
          'néng',
          'bāng',
          'wǒ',
          'yíxià',
          'ma',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 6,
      isFinal: false,
      korean: '좀 생각해 보다.',
      chinese: {
        hanzi: ['想想'],
        pinyin: ['xiǎngxiang'],
      },
    },
    {
      id: 'sentence10',
      level: 7,
      isFinal: false,
      korean: '내가 좀 생각해볼게(내가 좀 생각하게 해줘)',
      chinese: {
        hanzi: ['让', '我', '想想'],
        pinyin: ['ràng', 'wǒ', 'xiǎngxiang'],
      },
    },
    {
      id: 'sentence10',
      level: 8,
      isFinal: false,
      korean: '시간이 맞다(시간이 된다).',
      chinese: {
        hanzi: ['时间', '来得及'],
        pinyin: ['shíjiān', 'lái de jí'],
      },
    },
    {
      id: 'sentence10',
      level: 9,
      isFinal: false,
      korean: '만약 시간이 맞다면……',
      chinese: {
        hanzi: ['如果', '时间', '来得及', '的话'],
        pinyin: ['rúguǒ', 'shíjiān', 'lái de jí', 'de huà'],
      },
    },
    {
      id: 'sentence10',
      level: 10,
      isFinal: false,
      korean: '내가 좀 생각해볼게… 만약 시간이 맞다면……',
      chinese: {
        hanzi: ['让', '我', '想想', '如果', '时间', '来得及', '的话'],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 11,
      isFinal: false,
      korean: '내가 좀 생각해볼게… 만약 시간이 맞으면 가능해.',
      chinese: {
        hanzi: ['让', '我', '想想', '如果', '时间', '来得及', '的话', '可以'],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
          'kěyǐ',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 12,
      isFinal: true,
      korean: 'B: 내가 좀 생각해볼게… 만약 시간이 맞으면 가능해.',
      chinese: {
        hanzi: [
          '让',
          '我',
          '想想',
          '如果',
          '时间',
          '来得及',
          '的话',
          '应该',
          '可以',
        ],
        pinyin: [
          'ràng',
          'wǒ',
          'xiǎngxiang',
          'rúguǒ',
          'shíjiān',
          'lái de jí',
          'de huà',
          'yīnggāi',
          'kěyǐ',
        ],
      },
    },
  ],

  week3: [
    // 31번
    {
      id: 'sentence11',
      level: 1,
      isFinal: false,
      korean: '비가 와.',
      chinese: {
        hanzi: ['下雨', '了'],
        pinyin: ['xià yǔ', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 2,
      isFinal: false,
      korean: '오늘 비가 와.',
      chinese: {
        hanzi: ['今天', '下雨', '了'],
        pinyin: ['jīntiān', 'xià yǔ', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 3,
      isFinal: false,
      korean: '오늘 비 오는데 그래도……',
      chinese: {
        hanzi: ['今天', '下雨', '了', '还'],
        pinyin: ['jīntiān', 'xià yǔ', 'le', 'hái'],
      },
    },
    {
      id: 'sentence11',
      level: 4,
      isFinal: false,
      korean: '오늘 비 오는데 그래도 나가?',
      chinese: {
        hanzi: ['今天', '下雨', '了', '还', '出去', '吗'],
        pinyin: ['jīntiān', 'xià yǔ', 'le', 'hái', 'chūqù', 'ma'],
      },
    },
    {
      id: 'sentence11',
      level: 5,
      isFinal: true,
      korean: 'A: 오늘 비 오는데 그래도 나갈 거야?',
      chinese: {
        hanzi: ['今天', '下', '雨', '了', '还', '要', '出去', '吗'],
        pinyin: ['jīntiān', 'xià', 'yǔ', 'le', 'hái', 'yào', 'chūqù', 'ma'],
      },
    },
    {
      id: 'sentence11',
      level: 6,
      isFinal: false,
      korean: '약속했어.',
      chinese: {
        hanzi: ['约好', '了'],
        pinyin: ['yuē hǎo', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 7,
      isFinal: false,
      korean: '이미 약속했어.',
      chinese: {
        hanzi: ['已经', '约好', '了'],
        pinyin: ['yǐjing', 'yuē hǎo', 'le'],
      },
    },
    {
      id: 'sentence11',
      level: 8,
      isFinal: true,
      korean: 'B: 어쨌든 이미 약속했잖아.',
      chinese: {
        hanzi: ['反正', '已经', '约', '好', '了'],
        pinyin: ['fǎnzhèng', 'yǐjing', 'yuē', 'hǎo', 'le'],
      },
    },

    // 2번
    {
      id: 'sentence12',
      level: 1,
      isFinal: false,
      korean: '일 어때?',
      chinese: {
        hanzi: ['工作', '怎么样'],
        pinyin: ['gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 2,
      isFinal: false,
      korean: '이 일 어때?',
      chinese: {
        hanzi: ['这', '份', '工作', '怎么样'],
        pinyin: ['zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 3,
      isFinal: false,
      korean: '이 일에 대해 어떻게 생각해?',
      chinese: {
        hanzi: ['觉得', '这', '份', '工作', '怎么样'],
        pinyin: ['juéde', 'zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 4,
      isFinal: true,
      korean: 'A: 너는 이 일에 대해 어떻게 생각해?(너는 이 일이 어떤 것 같아?)',
      chinese: {
        hanzi: ['你', '觉得', '这', '份', '工作', '怎么样'],
        pinyin: ['nǐ', 'juéde', 'zhè', 'fèn', 'gōngzuò', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence12',
      level: 5,
      isFinal: false,
      korean: '힘들어.',
      chinese: {
        hanzi: ['累'],
        pinyin: ['lèi'],
      },
    },
    {
      id: 'sentence12',
      level: 6,
      isFinal: false,
      korean: '좀 힘들어.',
      chinese: {
        hanzi: ['有点', '累'],
        pinyin: ['yǒudiǎn', 'lèi'],
      },
    },
    {
      id: 'sentence12',
      level: 7,
      isFinal: true,
      korean: 'B: 솔직히 말하면, 좀 힘들어.',
      chinese: {
        hanzi: ['说', '实话', '有点', '累'],
        pinyin: ['shuō', 'shíhuà', 'yǒudiǎn', 'lèi'],
      },
    },

    // 3번
    {
      id: 'sentence13',
      level: 1,
      isFinal: false,
      korean: '이 생각(이 아이디어)',
      chinese: {
        hanzi: ['这', '个', '想法'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ'],
      },
    },
    {
      id: 'sentence13',
      level: 2,
      isFinal: false,
      korean: '이 생각은 믿을 만해.',
      chinese: {
        hanzi: ['这', '个', '想法', '靠谱'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ', 'kàopǔ'],
      },
    },
    {
      id: 'sentence13',
      level: 3,
      isFinal: true,
      korean: 'A: 이 생각은 믿을 만해?',
      chinese: {
        hanzi: ['这', '个', '想法', '靠谱', '吗'],
        pinyin: ['zhè', 'ge', 'xiǎngfǎ', 'kàopǔ', 'ma'],
      },
    },
    {
      id: 'sentence13',
      level: 4,
      isFinal: false,
      korean: '위험이 있어.',
      chinese: {
        hanzi: ['有', '风险'],
        pinyin: ['yǒu', 'fēngxiǎn'],
      },
    },
    {
      id: 'sentence13',
      level: 5,
      isFinal: false,
      korean: '그래도 위험이 있어.',
      chinese: {
        hanzi: ['还是', '有', '风险'],
        pinyin: ['háishi', 'yǒu', 'fēngxiǎn'],
      },
    },
    {
      id: 'sentence13',
      level: 6,
      isFinal: true,
      korean: 'B: 내가 보기에는, 그래도 위험이 있어.',
      chinese: {
        hanzi: ['在', '我', '看来', '还是', '有', '风险'],
        pinyin: ['zài', 'wǒ', 'kànlai', 'háishi', 'yǒu', 'fēngxiǎn'],
      },
    },
    // 4번
    {
      id: 'sentence14',
      level: 1,
      isFinal: false,
      korean: '이 방안, 이 안',
      chinese: {
        hanzi: ['这', '个', '方案'],
        pinyin: ['zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 2,
      isFinal: false,
      korean: '이 방안에 동의하다.',
      chinese: {
        hanzi: ['同意', '这', '个', '方案'],
        pinyin: ['tóngyì', 'zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 3,
      isFinal: false,
      korean: '이 방안에 동의하지 않다.',
      chinese: {
        hanzi: ['不', '同意', '这', '个', '方案'],
        pinyin: ['bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn'],
      },
    },
    {
      id: 'sentence14',
      level: 4,
      isFinal: false,
      korean: '이 방안에 동의하지 않는 거야?',
      chinese: {
        hanzi: ['不', '同意', '这', '个', '方案', '吗'],
        pinyin: ['bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn', 'ma'],
      },
    },
    {
      id: 'sentence14',
      level: 5,
      isFinal: true,
      korean: 'A: 당신은 이 방안에 동의하지 않나요?',
      chinese: {
        hanzi: ['你', '不', '同意', '这', '个', '方案', '吗'],
        pinyin: ['nǐ', 'bù', 'tóngyì', 'zhè', 'ge', 'fāng’àn', 'ma'],
      },
    },
    {
      id: 'sentence14',
      level: 6,
      isFinal: false,
      korean: '한번 해보다, 시험 삼아 해보다.',
      chinese: {
        hanzi: ['试试'],
        pinyin: ['shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 7,
      isFinal: false,
      korean: '소규모로 한번 해보다.',
      chinese: {
        hanzi: ['小', '规模', '试试'],
        pinyin: ['xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 8,
      isFinal: false,
      korean: '먼저 소규모로 한번 해보다.',
      chinese: {
        hanzi: ['先', '小', '规模', '试试'],
        pinyin: ['xiān', 'xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 9,
      isFinal: false,
      korean: '먼저 소규모로 한번 해볼 수 있어요.',
      chinese: {
        hanzi: ['可以', '先', '小', '规模', '试试'],
        pinyin: ['kěyǐ', 'xiān', 'xiǎo', 'guīmó', 'shìshi'],
      },
    },
    {
      id: 'sentence14',
      level: 10,
      isFinal: false,
      korean: '제 말은 먼저 소규모로 한번 해볼 수 있어요.',
      chinese: {
        hanzi: ['我', '的', '意思', '是', '可以', '先', '小', '规模', '试试'],
        pinyin: [
          'wǒ',
          'de',
          'yìsi',
          'shì',
          'kěyǐ',
          'xiān',
          'xiǎo',
          'guīmó',
          'shìshi',
        ],
      },
    },
    {
      id: 'sentence14',
      level: 11,
      isFinal: true,
      korean: 'B: 아니요, 제 말은 먼저 소규모로 한번 해볼 수 있다는 뜻이에요.',
      chinese: {
        hanzi: [
          '不是',
          '我',
          '的',
          '意思',
          '是',
          '可以',
          '先',
          '小',
          '规模',
          '试试',
        ],
        pinyin: [
          'bú shì',
          'wǒ',
          'de',
          'yìsi',
          'shì',
          'kěyǐ',
          'xiān',
          'xiǎo',
          'guīmó',
          'shìshi',
        ],
      },
    },
    // 5번
    {
      id: 'sentence15',
      level: 1,
      isFinal: false,
      korean: '이번 출장',
      chinese: {
        hanzi: ['这次', '出差'],
        pinyin: ['zhècì', 'chūchāi'],
      },
    },
    {
      id: 'sentence15',
      level: 2,
      isFinal: false,
      korean: '이번 출장 어때?',
      chinese: {
        hanzi: ['这次', '出差', '怎么样'],
        pinyin: ['zhècì', 'chūchāi', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence15',
      level: 3,
      isFinal: true,
      korean: 'A: 이번 출장 느낌은 어때?',
      chinese: {
        hanzi: ['这次', '出差', '感觉', '怎么样'],
        pinyin: ['zhècì', 'chūchāi', 'gǎnjué', 'zěnmeyàng'],
      },
    },
    {
      id: 'sentence15',
      level: 4,
      isFinal: false,
      korean: '얻은 게 많아(수확이 커).',
      chinese: {
        hanzi: ['收获', '大'],
        pinyin: ['shōuhuò', 'dà'],
      },
    },

    {
      id: 'sentence15',
      level: 5,
      isFinal: false,
      korean: '전반적으로 보면, 얻은 게 많아.',
      chinese: {
        hanzi: ['总的来说', '收获', '大'],
        pinyin: ['zǒng de lái shuō', 'shōuhuò', 'dà'],
      },
    },
    {
      id: 'sentence15',
      level: 6,
      isFinal: false,
      korean: '전반적으로 보면, 얻은 게 꽤 많아.',
      chinese: {
        hanzi: ['总', '的', '来', '说', '收获', '挺', '大', '的'],
        pinyin: ['zǒng', 'de', 'lái', 'shuō', 'shōuhuò', 'tǐng', 'dà', 'de'],
      },
    },

    {
      id: 'sentence15',
      level: 7,
      isFinal: true,
      korean: 'B: 전반적으로 보면, 얻은 게 그래도 꽤 많아.',
      chinese: {
        hanzi: ['总', '的', '来', '说', '收获', '还是', '挺', '大', '的'],
        pinyin: [
          'zǒng',
          'de',
          'lái',
          'shuō',
          'shōuhuò',
          'háishi',
          'tǐng',
          'dà',
          'de',
        ],
      },
    },
  ],

  week4: [
    // 31번
    {
      id: 'sentence16',
      level: 1,
      isFinal: false,
      korean: '더 안전해(비교적 안전해).',
      chinese: {
        hanzi: ['比较', '安全'],
        pinyin: ['bǐjiào', 'ānquán'],
      },
    },
    {
      id: 'sentence16',
      level: 2,
      isFinal: false,
      korean: '나가는 게 더 안전해.',
      chinese: {
        hanzi: ['出门', '比较', '安全'],
        pinyin: ['chūmén', 'bǐjiào', 'ānquán'],
      },
    },
    {
      id: 'sentence16',
      level: 3,
      isFinal: true,
      korean: 'A: 좀 일찍 나가는 게 더 안전해.',
      chinese: {
        hanzi: ['早点', '出门', '比较', '安全'],
        pinyin: ['zǎodiǎn', 'chūmén', 'bǐjiào', 'ānquán'],
      },
    },
    {
      id: 'sentence16',
      level: 4,
      isFinal: false,
      korean: '너무 급해(너무 촉박해).',
      chinese: {
        hanzi: ['太', '赶'],
        pinyin: ['tài', 'gǎn'],
      },
    },
    {
      id: 'sentence16',
      level: 5,
      isFinal: false,
      korean: '너무 급하지 않을 거야.',
      chinese: {
        hanzi: ['不', '会', '太', '赶'],
        pinyin: ['bú', 'huì', 'tài', 'gǎn'],
      },
    },
    {
      id: 'sentence16',
      level: 6,
      isFinal: false,
      korean: '길에서도 너무 급하지는 않을 거야.',
      chinese: {
        hanzi: ['路上', '也', '不', '会', '太', '赶'],
        pinyin: ['lùshang', 'yě', 'bú', 'huì', 'tài', 'gǎn'],
      },
    },
    {
      id: 'sentence16',
      level: 7,
      isFinal: true,
      korean: 'B: 일리가 있어, 길에서도 너무 급하지 않을 거야.',
      chinese: {
        hanzi: ['有', '道理', '路上', '也', '不', '会', '太', '赶'],
        pinyin: ['yǒu', 'dàolǐ', 'lùshang', 'yě', 'bú', 'huì', 'tài', 'gǎn'],
      },
    },
    // 2번
    {
      id: 'sentence17',
      level: 1,
      isFinal: false,
      korean: '저쪽 길로 가다.',
      chinese: {
        hanzi: ['走', '那', '条', '路'],
        pinyin: ['zǒu', 'nà', 'tiáo', 'lù'],
      },
    },
    {
      id: 'sentence17',
      level: 2,
      isFinal: false,
      korean: '저쪽 길로 안 가다.',
      chinese: {
        hanzi: ['不', '走', '那', '条', '路'],
        pinyin: ['bù', 'zǒu', 'nà', 'tiáo', 'lù'],
      },
    },
    {
      id: 'sentence17',
      level: 3,
      isFinal: false,
      korean: '왜 저쪽 길로 안 가?',
      chinese: {
        hanzi: ['为什么', '不', '走', '那', '条', '路'],
        pinyin: ['wèishénme', 'bù', 'zǒu', 'nà', 'tiáo', 'lù'],
      },
    },
    {
      id: 'sentence17',
      level: 4,
      isFinal: false,
      korean: '더 빨리 도착해.',
      chinese: {
        hanzi: ['更', '快', '到'],
        pinyin: ['gèng', 'kuài', 'dào'],
      },
    },
    {
      id: 'sentence17',
      level: 5,
      isFinal: false,
      korean: '더 빨리 도착할 수 있어.',
      chinese: {
        hanzi: ['能', '更', '快', '到'],
        pinyin: ['néng', 'gèng', 'kuài', 'dào'],
      },
    },
    {
      id: 'sentence17',
      level: 6,
      isFinal: false,
      korean: '더 빨리 도착할 수 있지 않아?',
      chinese: {
        hanzi: ['不', '是', '能', '更', '快', '到', '吗'],
        pinyin: ['bú', 'shì', 'néng', 'gèng', 'kuài', 'dào', 'ma'],
      },
    },
    {
      id: 'sentence17',
      level: 7,
      isFinal: true,
      korean: 'A: 왜 저쪽 길로 안 가? 더 빨리 도착할 수 있지 않아?',
      chinese: {
        hanzi: [
          '为什么',
          '不',
          '走',
          '那',
          '条',
          '路',
          '不',
          '是',
          '能',
          '更',
          '快',
          '到',
          '吗',
        ],
        pinyin: [
          'wèishénme',
          'bù',
          'zǒu',
          'nà',
          'tiáo',
          'lù',
          'bú',
          'shì',
          'néng',
          'gèng',
          'kuài',
          'dào',
          'ma',
        ],
      },
    },
    {
      id: 'sentence17',
      level: 8,
      isFinal: false,
      korean: '더 급해.',
      chinese: {
        hanzi: ['更', '急'],
        pinyin: ['gèng', 'jí'],
      },
    },
    {
      id: 'sentence17',
      level: 9,
      isFinal: false,
      korean: '시간이 더 급한거니까.',
      chinese: {
        hanzi: ['时间', '上', '更', '急'],
        pinyin: ['shíjiān', 'shang', 'gèng', 'jí'],
      },
    },
    {
      id: 'sentence17',
      level: 10,
      isFinal: false,
      korean: '지금은 시간이 더 급한거니까.',
      chinese: {
        hanzi: ['现在', '是', '时间', '上', '更', '急'],
        pinyin: ['xiànzài', 'shì', 'shíjiān', 'shang', 'gèng', 'jí'],
      },
    },
    {
      id: 'sentence17',
      level: 11,
      isFinal: false,
      korean: '저쪽으로 가다.',
      chinese: {
        hanzi: ['走', '那边'],
        pinyin: ['zǒu', 'nàbiān'],
      },
    },
    {
      id: 'sentence17',
      level: 12,
      isFinal: false,
      korean: '저쪽으로 가자.',
      chinese: {
        hanzi: ['走', '那边', '吧'],
        pinyin: ['zǒu', 'nàbiān', 'ba'],
      },
    },
    {
      id: 'sentence17',
      level: 13,
      isFinal: false,
      korean: '저쪽으로 가자. 우리 지금은 시간이 더 급한거니까.',
      chinese: {
        hanzi: [
          '走',
          '那边',
          '吧',
          '我们',
          '现在',
          '是',
          '时间',
          '上',
          '更',
          '急',
        ],
        pinyin: [
          'zǒu',
          'nàbiān',
          'ba',
          'wǒmen',
          'xiànzài',
          'shì',
          'shíjiān',
          'shang',
          'gèng',
          'jí',
        ],
      },
    },
    {
      id: 'sentence17',
      level: 14,
      isFinal: false,
      korean: '그럼 저쪽으로 가자. 우리 지금은 시간이 더 급한거니까.',
      chinese: {
        hanzi: [
          '那',
          '走',
          '那边',
          '吧',
          '我们',
          '现在',
          '是',
          '时间',
          '上',
          '更',
          '急',
        ],
        pinyin: [
          'nà',
          'zǒu',
          'nàbiān',
          'ba',
          'wǒmen',
          'xiànzài',
          'shì',
          'shíjiān',
          'shang',
          'gèng',
          'jí',
        ],
      },
    },
    {
      id: 'sentence17',
      level: 15,
      isFinal: true,
      korean:
        'B: 그러네, 그럼 저쪽으로 가자. 우리 지금은 시간이 더 급한거니까.',
      chinese: {
        hanzi: [
          '也',
          '是',
          '那',
          '走',
          '那边',
          '吧',
          '我们',
          '现在',
          '是',
          '时间',
          '上',
          '更',
          '急',
        ],
        pinyin: [
          'yě',
          'shì',
          'nà',
          'zǒu',
          'nàbiān',
          'ba',
          'wǒmen',
          'xiànzài',
          'shì',
          'shíjiān',
          'shang',
          'gèng',
          'jí',
        ],
      },
    },
    // 3번
    {
      id: 'sentence18',
      level: 1,
      isFinal: false,
      korean: '팀워크, 팀 협력',
      chinese: {
        hanzi: ['团队', '合作'],
        pinyin: ['tuánduì', 'hézuò'],
      },
    },
    {
      id: 'sentence18',
      level: 2,
      isFinal: false,
      korean: '팀워크에 의지하다(덕분이다)',
      chinese: {
        hanzi: ['靠', '团队', '合作'],
        pinyin: ['kào', 'tuánduì', 'hézuò'],
      },
    },
    {
      id: 'sentence18',
      level: 3,
      isFinal: false,
      korean: '주로(거의) 팀워크에 의지하다(덕분이다).?',
      chinese: {
        hanzi: ['主要', '靠', '团队', '合作'],
        pinyin: ['zhǔyào', 'kào', 'tuánduì', 'hézuò'],
      },
    },
    {
      id: 'sentence18',
      level: 4,
      isFinal: true,
      korean: 'A: 이번 성공은 주로(거의) 팀워크 덕분이야.',
      chinese: {
        hanzi: ['这次', '成功', '主要', '靠', '团队', '合作'],
        pinyin: ['zhècì', 'chénggōng', 'zhǔyào', 'kào', 'tuánduì', 'hézuò'],
      },
    },
    {
      id: 'sentence18',
      level: 5,
      isFinal: false,
      korean: '아주 열심히 해.',
      chinese: {
        hanzi: ['很', '努力'],
        pinyin: ['hěn', 'nǔlì'],
      },
    },
    {
      id: 'sentence18',
      level: 6,
      isFinal: false,
      korean: '모두 다 열심히 했어.',
      chinese: {
        hanzi: ['大家', '都', '很', '努力'],
        pinyin: ['dàjiā', 'dōu', 'hěn', 'nǔlì'],
      },
    },
    {
      id: 'sentence18',
      level: 7,
      isFinal: true,
      korean: 'B: 맞아, 모두 다 열심히 했어.',
      chinese: {
        hanzi: ['没', '错', '大家', '都', '很', '努力'],
        pinyin: ['méi', 'cuò', 'dàjiā', 'dōu', 'hěn', 'nǔlì'],
      },
    },
    // 4번
    {
      id: 'sentence19',
      level: 1,
      isFinal: false,
      korean: '3번 회의실에서.',
      chinese: {
        hanzi: ['在', '三', '号', '会议室'],
        pinyin: ['zài', 'sān', 'hào', 'huìyìshì'],
      },
    },
    {
      id: 'sentence19',
      level: 2,
      isFinal: false,
      korean: '3번 회의실에서 회의하다.',
      chinese: {
        hanzi: ['在', '三', '号', '会议室', '开', '会'],
        pinyin: ['zài', 'sān', 'hào', 'huìyìshì', 'kāi', 'huì'],
      },
    },
    {
      id: 'sentence19',
      level: 3,
      isFinal: false,
      korean: '3번 회의실에서 회의한 거야.',
      chinese: {
        hanzi: ['是', '在', '三', '号', '会议室', '开', '会'],
        pinyin: ['shì', 'zài', 'sān', 'hào', 'huìyìshì', 'kāi', 'huì'],
      },
    },
    {
      id: 'sentence19',
      level: 4,
      isFinal: false,
      korean: '우리는 3번 회의실에서 회의했어.',
      chinese: {
        hanzi: ['我们', '是', '在', '三', '号', '会议室', '开', '会'],
        pinyin: ['wǒmen', 'shì', 'zài', 'sān', 'hào', 'huìyìshì', 'kāi', 'huì'],
      },
    },
    {
      id: 'sentence19',
      level: 5,
      isFinal: false,
      korean: '어제 우리는 3번 회의실에서 회의했어.',
      chinese: {
        hanzi: ['昨天', '我们', '是', '在', '三', '号', '会议室', '开', '会'],
        pinyin: [
          'zuótiān',
          'wǒmen',
          'shì',
          'zài',
          'sān',
          'hào',
          'huìyìshì',
          'kāi',
          'huì',
        ],
      },
    },
    {
      id: 'sentence19',
      level: 6,
      isFinal: true,
      korean: 'A: 어제 우리 3번 회의실에서 회의한 거지?',
      chinese: {
        hanzi: [
          '昨天',
          '我们',
          '是',
          '在',
          '三',
          '号',
          '会议室',
          '开',
          '会',
          '吧',
        ],
        pinyin: [
          'zuótiān',
          'wǒmen',
          'shì',
          'zài',
          'sān',
          'hào',
          'huìyìshì',
          'kāi',
          'huì',
          'ba',
        ],
      },
    },
    {
      id: 'sentence19',
      level: 7,
      isFinal: false,
      korean: '그 방이야.',
      chinese: {
        hanzi: ['是', '那', '间'],
        pinyin: ['shì', 'nà', 'jiān'],
      },
    },
    {
      id: 'sentence19',
      level: 8,
      isFinal: false,
      korean: '바로 그 방이야.',
      chinese: {
        hanzi: ['就', '是', '那', '间'],
        pinyin: ['jiù', 'shì', 'nà', 'jiān'],
      },
    },
    {
      id: 'sentence19',
      level: 9,
      isFinal: true,
      korean: 'B: 먼저 소규모로 한번 해볼 수 있어요.',
      chinese: {
        hanzi: ['对对对', '就', '是', '那', '间'],
        pinyin: ['duì duì duì', 'jiù', 'shì', 'nà', 'jiān'],
      },
    },
    // 5번
    {
      id: 'sentence20',
      level: 1,
      isFinal: false,
      korean: '시간을 절약해.',
      chinese: {
        hanzi: ['省', '时间'],
        pinyin: ['shěng', 'shíjiān'],
      },
    },
    {
      id: 'sentence20',
      level: 2,
      isFinal: false,
      korean: '시간을 더 절약해.',
      chinese: {
        hanzi: ['更', '省', '时间'],
        pinyin: ['gèng', 'shěng', 'shíjiān'],
      },
    },
    {
      id: 'sentence20',
      level: 3,
      isFinal: true,
      korean: 'A: 이 방법이 시간을 더 절약해.',
      chinese: {
        hanzi: ['这', '个', '方法', '更', '省', '时间'],
        pinyin: ['zhè', 'ge', 'fāngfǎ', 'gèng', 'shěng', 'shíjiān'],
      },
    },
    {
      id: 'sentence20',
      level: 4,
      isFinal: false,
      korean: '효율이 좋아.',
      chinese: {
        hanzi: ['效率', '高'],
        pinyin: ['xiàolǜ', 'gāo'],
      },
    },

    {
      id: 'sentence20',
      level: 5,
      isFinal: false,
      korean: '효율이 훨씬 좋아.',
      chinese: {
        hanzi: ['效率', '高', '多', '了'],
        pinyin: ['xiàolǜ', 'gāo', 'duō', 'le'],
      },
    },
    {
      id: 'sentence20',
      level: 6,
      isFinal: false,
      korean: '나도 (그렇게) 생각해(동의해), 효율이 훨씬 좋아.',
      chinese: {
        hanzi: ['我', '也', '觉得', '效率', '高', '多', '了'],
        pinyin: ['wǒ', 'yě', 'juéde', 'xiàolǜ', 'gāo', 'duō', 'le'],
      },
    },

    {
      id: 'sentence20',
      level: 7,
      isFinal: true,
      korean: 'B: 나도 그렇게 생각해, 효율이 훨씬 좋아.',
      chinese: {
        hanzi: ['我', '也', '这么', '觉得', '效率', '高', '多', '了'],
        pinyin: ['wǒ', 'yě', 'zhème', 'juéde', 'xiàolǜ', 'gāo', 'duō', 'le'],
      },
    },
  ],
};

// 전역 변수로 내보내기
window.sentenceData = sentenceData;
