const sentenceData = {
  week1: [
    // 1번
    {
      id: 'sentence1',
      level: 1,
      isFinal: false,
      korean: '꾸준히 해야 한다.',
      chinese: {
        hanzi: ['要', '坚持'],
        pinyin: ['yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 2,
      isFinal: false,
      korean: '공부는 꾸준히 해야 한다.',
      chinese: {
        hanzi: ['学习', '要', '坚持'],
        pinyin: ['xuéxí', 'yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 3,
      isFinal: false,
      korean: '공부는 꾸준히 해야 하고, ...하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú yào'],
      },
    },
    {
      id: 'sentence1',
      level: 4,
      isFinal: true,
      korean: '공부는 꾸준히 해야 하고, 중간에 포기하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要', '半途', '而', '废'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú yào', 'bàntú', 'ér', 'fèi'],
      },
    },

    // 2번
    {
      id: 'sentence2',
      level: 1,
      isFinal: false,
      korean: '많이 피곤하다.',
      chinese: {
        hanzi: ['很', '累'],
        pinyin: ['hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 2,
      isFinal: false,
      korean: '비록 많이 피곤하지만, ......',
      chinese: {
        hanzi: ['尽管', '很', '累'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 3,
      isFinal: false,
      korean: '비록 많이 피곤하지만, 그래도 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '做', '完'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi', 'yě', 'yào', 'zuò', 'wán'],
      },
    },
    {
      id: 'sentence2',
      level: 4,
      isFinal: true,
      korean: '비록 많이 피곤하지만, 그래도 일을 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '把', '工作', '做', '完'],
        pinyin: [
          'jǐnguǎn',
          'hěn',
          'lèi',
          'yě',
          'yào',
          'bǎ',
          'gōngzuò',
          'zuò',
          'wán',
        ],
      },
    },

    // 3번
    {
      id: 'sentence3',
      level: 1,
      isFinal: false,
      korean: '시간을 바꾸다.',
      chinese: {
        hanzi: ['改', '时间'],
        pinyin: ['gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 2,
      isFinal: false,
      korean: '갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['临时', '改', '时间'],
        pinyin: ['línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 3,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 4,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 5,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '又', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'yòu', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 6,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '我们', '又', '得', '加班'],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
        ],
      },
    },
    {
      id: 'sentence3',
      level: 7,
      isFinal: true,
      korean:
        '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 해. 짜증 나지 않냐.',
      chinese: {
        hanzi: [
          '领导',
          '临时',
          '改',
          '时间',
          '我们',
          '又',
          '得',
          '加班',
          '你',
          '说',
          '烦',
          '不烦',
        ],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
          'nǐ',
          'shuō',
          'fán',
          'bu fán',
        ],
      },
    },
    // 4번
    {
      id: 'sentence4',
      level: 1,
      isFinal: false,
      korean: '선택을 하지 못하다.',
      chinese: {
        hanzi: ['做不出', '选择'],
        pinyin: ['zuò bu chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 2,
      isFinal: false,
      korean: '지금 선택을 하지 못하고 있다.',
      chinese: {
        hanzi: ['现在', '做不出', '选择'],
        pinyin: ['xiànzài', 'zuò bu chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 3,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면……',
      chinese: {
        hanzi: ['现在', '做', '不', '出', '选择', '换', '句', '话', '说'],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 4,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상……',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就是',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù shì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 5,
      isFinal: false,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就是',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù shì',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 6,
      isFinal: true,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하고 있는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就',
          '是',
          '在',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù',
          'shì',
          'zài',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    // 5번
    {
      id: 'sentence5',
      level: 1,
      isFinal: false,
      korean: '가격이 비싸다.',
      chinese: {
        hanzi: ['价格', '贵'],
        pinyin: ['jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 2,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데……',
      chinese: {
        hanzi: ['不怕', '价格', '贵'],
        pinyin: ['bú pà', 'jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 3,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데, ……이 걱정이다.',
      chinese: {
        hanzi: ['不怕', '价格', '贵', '就', '怕'],
        pinyin: ['bú pà', 'jiàgé', 'guì', 'jiù', 'pà'],
      },
    },
    {
      id: 'sentence5',
      level: 4,
      isFinal: true,
      korean: '가격이 비싼 건 괜찮은데, 품질이 안 좋을까 봐 걱정이다.',
      chinese: {
        hanzi: ['不怕', '价格', '贵', '就', '怕', '质量', '不', '好'],
        pinyin: ['bú pà', 'jiàgé', 'guì', 'jiù', 'pà', 'zhìliàng', 'bù', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 1,
      isFinal: false,
      korean: '환경(분위기)이 좋다.',
      chinese: {
        hanzi: ['环境', '好'],
        pinyin: ['huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 2,
      isFinal: false,
      korean: '이 식당은 분위기가 좋다.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 3,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好是好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo shì hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 4,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데, 근데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好是好', '可'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo shì hǎo', 'kě'],
      },
    },
    {
      id: 'sentence6',
      level: 5,
      isFinal: true,
      korean: '이 식당 분위기는 좋긴 한데, (근데) 맛은 평범해.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好', '是好', '可', '味道', '一般'],
        pinyin: [
          'zhè',
          'jiā',
          'cāntīng',
          'huánjìng',
          'hǎo',
          'shì hǎo',
          'kě',
          'wèidào',
          'yìbān',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 1,
      isFinal: false,
      korean: '도착했다.',
      chinese: {
        hanzi: ['到', '了'],
        pinyin: ['dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 2,
      isFinal: false,
      korean: '제시간에 도착했다.',
      chinese: {
        hanzi: ['准时', '到', '了'],
        pinyin: ['zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 3,
      isFinal: false,
      korean: '설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['居然', '准时', '到', '了'],
        pinyin: ['jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 4,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['你', '居然', '准时', '到', '了'],
        pinyin: ['nǐ', 'jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 5,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고? 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 6,
      isFinal: true,
      korean: '네가 설마 제시간에 도착했다고? 진짜 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '真是',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'zhēnshì',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence8',
      level: 1,
      isFinal: false,
      korean: '걱정하다.',
      chinese: {
        hanzi: ['担心'],
        pinyin: ['dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 2,
      isFinal: false,
      korean: '걱정하지 마.',
      chinese: {
        hanzi: ['别', '担心'],
        pinyin: ['bié', 'dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 3,
      isFinal: true,
      korean: '걱정 마, 내가 있잖아.',
      chinese: {
        hanzi: ['别', '担心', '有', '我', '呢'],
        pinyin: ['bié', 'dānxīn', 'yǒu', 'wǒ', 'ne'],
      },
    },
    {
      id: 'sentence9',
      level: 1,
      isFinal: false,
      korean: '나에게 알려줘.',
      chinese: {
        hanzi: ['告诉', '我'],
        pinyin: ['gàosu', 'wǒ'],
      },
    },
    {
      id: 'sentence9',
      level: 2,
      isFinal: false,
      korean: '나에게 알려줘(봐).',
      chinese: {
        hanzi: ['告诉', '我', '吧'],
        pinyin: ['gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 3,
      isFinal: false,
      korean: '미리 나한테 알려줘.',
      chinese: {
        hanzi: ['提前', '告诉', '我', '吧'],
        pinyin: ['tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 4,
      isFinal: false,
      korean: '미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['得', '提前', '告诉', '我', '吧'],
        pinyin: ['děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 5,
      isFinal: false,
      korean: '어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['怎么说也', '得', '提前', '告诉', '我', '吧'],
        pinyin: ['zěnme shuō yě', 'děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 6,
      isFinal: true,
      korean: '그는 아무리 바빠도, 어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: [
          '他',
          '再',
          '忙',
          '怎么',
          '说',
          '也',
          '得',
          '提前',
          '告诉',
          '我',
          '吧',
        ],
        pinyin: [
          'tā',
          'zài',
          'máng',
          'zěnme',
          'shuō',
          'yě',
          'děi',
          'tíqián',
          'gàosu',
          'wǒ',
          'ba',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 1,
      isFinal: false,
      korean: '지금은 …할 때다.',
      chinese: {
        hanzi: ['现在', '是', '时候'],
        pinyin: ['xiànzài', 'shì', 'shíhou'],
      },
    },
    {
      id: 'sentence10',
      level: 2,
      isFinal: false,
      korean: '이제는 …할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候了'],
        pinyin: ['xiànzài', 'shì', 'shíhou le'],
      },
    },
    {
      id: 'sentence10',
      level: 3,
      isFinal: false,
      korean: '이제는 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候了', '得', '谈一谈'],
        pinyin: ['xiànzài', 'shì', 'shíhou le', 'děi', 'tán yi tán'],
      },
    },
    {
      id: 'sentence10',
      level: 4,
      isFinal: false,
      korean: '이제는 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '得', '认真', '谈一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'děi',
          'rènzhēn',
          'tán yi tán',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 5,
      isFinal: true,
      korean: '이제는 우리 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '我们', '得', '认真', '谈', '一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'wǒmen',
          'děi',
          'rènzhēn',
          'tán',
          'yi tán',
        ],
      },
    },
  ],
};

// 전역 변수로 내보내기
window.sentenceData = sentenceData;
